version: '3.8'
services:
    api-service:
        build: .
        container_name: api-service
        volumes:
            - ./api/:/usr/src/app/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
        restart: always

    mariadb:
        image: mariadb
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: maria
            MYSQL_PASSWORD: maria
        volumes:
            - ./mariadb:/var/lib/mysql

    adminer:
        image: adminer
        container_name: adminer
        depends_on:
            - mariadb
        ports:
            - 8080:8080